name: C/C++ CI

on:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make install
      run: make install
    - name: make distcheck
      run: make distcheck
